StoryAbisUTS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story7/urls.py
from django.urls import path
from .views import index

app_name = 'story7'

urlpatterns = [
    path('', index, name='index'),
]

story8/urls.py
from django.urls import path
from .views import bookSearchView, fungsi_data

app_name = 'story8'

urlpatterns = [
    path('story8/', bookSearchView, name='book'),
    path('data/', fungsi_data, name='fungsi_data')
]

story9/urls.py
from django.urls import path
from .views import logIn, signUp, logOut

app_name = 'story9'

urlpatterns = [
    path('login/', logIn, name='login'),
    path('signup/', signUp, name='signup'),
    path('logout/', logOut, name='logout'),
]

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signIn-username',
        'placeholder' : 'Username',
        'type' : 'text',
        'style' : 'width: 20vw;',
        'required' : True
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signIn-password',
        'placeholder' : 'Password',
        'type' : 'password',
        'style' : 'width: 20vw;',
        'required' : True
    }))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="First name", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-firstName',
        'placeholder' : 'First name',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    last_name = forms.CharField(label="Last name", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Last name',
        'id' : 'signUp-lastName',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-username',
        'placeholder' : 'Username',
        'type' : 'text',
        'style' : 'width: 30vw;',
        'required' : True
    }))

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-password1',
        'placeholder' : 'Password',
        'type' : 'password',
        'style' : 'width: 30vw;',
        'required' : True
    }))
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={
        'class' : 'form-control',
        'id' : 'signUp-password2',
        'placeholder' : 'Confirm Password',
        'type' : 'password',
        'style' : 'width: 30vw;',
        'required' : True
    }))

class Meta:
    model = User
    fields = ['first_name', 'last_name', 'username', 'password1', 'password2']

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index.html")

story8/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
import json
from django.core import serializers
import requests

# Create your views here.
def bookSearchView(request):
    return render(request, 'book.html')

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    return JsonResponse(ret.json())

story9/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, SignUpForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Create your views here.
def logIn(request):
    if request.method == "POST":
        form = LoginForm(data = request.POST)

        if form.is_valid():
            usernameInput = request.POST["username"]
            passwordInput = request.POST["password"]

            print(usernameInput, passwordInput)
            user = authenticate(request, username = usernameInput, password = passwordInput)

            if user is not None:
                login(request, user)
                return redirect('/login')

        else:
            messages.error(request, 'Invalid entry')

    else:
        form = LoginForm()

    context = {
        "form" : form,
    }

    return render(request, "login.html", context)

def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/login")

        else:
            for msg in form.error_messages:
                messages.error(request, 'Invalid entry')

    else:
        form = SignUpForm()

    context = {
        'form' : form
    }

    return render(request, "signup.html", context)

def logOut(request):
    logout(request)
    return redirect("/login")

story7/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- ICONS -->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">   
    <!-- FONTS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
    <!-- CUSTOM CSS -->     
    <link rel="stylesheet" type="text/css" href="{% static 'css/story8.css' %}">   
    <link rel="stylesheet" type="text/css" href="{% static 'css/story7.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/story9.css' %}">   
    
    
    <title>Ayuka's</title>
  </head>
  <body>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="{% static 'js/story7.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="{% static 'js/story8.js' %}"></script>


  </body>
</html>

story7/templates/navbar.html
<nav id="sidebar" class="mb-3">
    <li class="active">
        <a href="#homeSubmenu" data-toggle="collapse" type=button aria-expanded="false" class="dropdown-toggle btn-toggle">Menu</a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
            <li>
                <a href="{% url 'story7:index' %}">Story7</a>
            </li>
            <li>
                <a href="{% url 'story8:book' %}">Story8</a>
            </li>
            <li>
                <a href="{% url 'story9:login' %}">Story9</a>
            </li>
        </ul>
    </li>
</nav>

story8/templates/book.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="main-booksearch">
    <div class="row">

        <!-- Sidebar -->
        <nav id="sidebar2" class="left-container col-3">
            <div>
                <div class="sidebar-header header-about">
                    <h1>Book<br>Search</h1>
                    <br>
                    <h2> Are you bored? </h2>
                    <p>
                    Try to find a variety of book <br>
                    information that will be <br>
                    useful for you now!<br>
                    <br>
                </div>

                <ul class="list-unstyled components ml-3">
                    <p>Menu</p>
                    <div id="sidebarIn" class="active">
                        <li><a href="{% url 'story7:index' %}">Story7</a></li>
                        <li><a href="{% url 'story8:book' %}">Story8</a></li>
                    </div>
                </ul>
            </div>
        </nav>
        <!-- End sidebar -->
        
    

        <!-- Page Content -->
        <div class="right-container mt-5">

            <!-- Sidebar toggle button -->
            <div id="sidebar-toggle col">
                <nav class="navbar navbar-expand-lg navbar-light" id="sidebar-container">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fa fa-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>            
                    </div>
                </nav>
            </div>

            <!-- Book search content -->
            <div class="container ml-5 mt-5">
                <div class="bookSearch-title">
                    <h1><i class="fa fa-search"></i><span class="ml-3">BOOK SEARCH</span></h1>
                    
                </div>
        
                <div class="search-bar">
                    <input class="form-control" type="text" placeholder="What are you looking for?" id="search-input" name="search">
                </div>
        
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col" class="align-center">#</th>
                            <th scope="col" class="align-center">Cover</th>
                            <th scope="col" class="align-center">Title</th>
                            <th scope="col" class="align-center">Authors</th>
                            <th scope="col" class="align-center">Publisher</th>
                            <th scope="col" class="align-center">Published Date</th>
                        </tr>
                    </thead>
                    <tbody id="search-result"></tbody>
                </table>

            </div>
            <!-- End book search content -->
        </div>
        <!-- End page content -->
    </div>
</div>      

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'js/story8.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar2').toggleClass('active');
            });

    });

</script>

{% endblock content %}

story9/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="main-story10 d-flex flex-column justify-content-center" theme="dark">
    <div class="row">
        <div class="left-side d-flex flex-column justify-content-start col-3">

                <!-- Sidebar Menu -->
                <div class="ml-5 mt-5 mb-3">
                    {% include 'navbar.html' %}
                </div>

                {% if user.is_authenticated == False %}
                
                <!-- Header Text -->
                <div class="header-about ml-5 mt-3">
                    <h1>Hello, <br> there. </h1>
                    <br>
                    <h2> Ssst, there's a little secret for you. </h2>
                    <p>
                    Try to sign up and log in <br>
                    to know what is the secret!<br>
                    <br>
                </div>

                {% else %}

                <!-- Header Text -->
                <div class="header-about ml-5 mt-3">
                    <h1>Hello, <br> there. </h1>
                    <br>
                    <h2> Yay! You did it. </h2>
                </div>

                {% endif %}

        
        </div>

        <div class="right-page col">
            {% if user.is_authenticated == False %}
            <div class="login content mx-5 my-5">
                {% if messages %}
                    {% for message in messages %}
                        <p>{{message}}</p>
                    {% endfor %}
                {% endif %}
                <div class="title">
                    <h3>Sign in</h3>
                    <br>
                </div>
                <div class="login-form">
                    <form method="POST">
                        {% csrf_token %} 
                        {{ form }}
                        <div>
                            <button type="submit" name="btn-login" id="btn-logIn" class="btn btn-dark mt-4">LOGIN</button>
                        </div>
                    </form>
                </div>

                <div class="info mt-5">
                    <p>
                        Don't have an account? <a class="sign-up-in-link" href="{% url 'story9:signup' %}"><strong>Sign up.</strong></a>
                    </p>
                </div>
            </div>

            {% else %}
                <div class="success mt-5 ml-5">
                    <div class="btn-logout">
                        <form action="{% url 'story9:logout' %}">
                            <input type="submit" id="btn-logOut" class="btn btn-dark" value="Log out">
                        </form>
                    </div>

                    <div class="greeting mt-5">
                        <h3>Welcome, </h3>
                        <h1 style="font-weight: 800px;"><span class="highlight">{{user.username}}.</span></h1>
                        <p> since you had succesfully get here, as you can see... yeah, <br>
                        this is the secret. I present to you.. some videos & musics that can raise your mood.</p>
                        <br>
                        <p> Here are the list! </p>
                        <br>
                        <h1 style="font-size: 30px; font-weight: 800px;"><span class="highlight">1. Stray Kids - Backdoor</span></h1>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/X-uJtV8ScYk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen><br></iframe>
                        <h1><br></h1>
                        <h1 style="font-size: 30px; font-weight: 800px;"><span class="highlight">2. Kim Seon-ho reacts to 'All the Times We Fell for Han Ji-pyeong in Start-Up' [ENG SUB]</span></h1>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/fajKpCEh8lQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen><br></iframe>
                        <h1><br></h1>

                        <div class="flex-container">
                            <div>
                                <iframe src="https://open.spotify.com/embed/track/4Bmk7JYOquhWmSMMW4WebM" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div>

                            <div>
                                <iframe src="https://open.spotify.com/embed/track/3t0Dw9zYFXK4ezJxbM3rbj" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"><br></iframe>
                            </div> 
                        </div>

                        <div class="flex-container">
                            <div>
                                <iframe src="https://open.spotify.com/embed/track/0u5FYJWJLcLzSN9S1Wb2ag" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div>

                            <div>
                                <iframe src="https://open.spotify.com/embed/track/3Dzso9Q2WwupEclqgxBZht" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div> 
                        </div>

                        <div class="flex-container">
                            <div>
                                <iframe src="https://open.spotify.com/embed/track/1fah1uAs7HeTYDlNftKr3K" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div>

                            <div>
                                <iframe src="https://open.spotify.com/embed/track/0y9fkzOaaQy4Up22BGUbIp" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div> 
                        </div>
                        <h1><br></h1>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock content %}

story9/templates/signup.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="main-story10 d-flex flex-column justify-content-center" theme="dark">
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}
    
    <div class="row">
        <div class="left-side d-flex flex-column justify-content-start col-3">
            <!-- Sidebar Menu -->
            <div class="ml-5 mt-5 mb-3">
                {% include 'navbar.html' %}
            </div>
            
            <!-- Header Text -->
            <div class="header-about ml-5 mt-3">
                <h1>Hello, <br> there. </h1>
                <br>
                <h2> Ssst, there's a little secret for you. </h2>
                <p>
                Try to sign up and log in <br>
                to know what is the secret!<br>
                <br>
            </div>
        
        </div>

        <div class="right-page col">
            <div class="login-content mx-5 my-5">

                <div class="title">
                    <h3>Create a new account</h3>
                    <br>
                </div>
            
            <div class="register-form">
                <form method="POST">
                    {% csrf_token %} 
                    {{ form }}
                    <div>
                        <button type="submit" name="btn-signup" id='btn-signUp' class="btn btn-dark mt-4">SIGN UP</button>
                    </div>
                </form>
            </div>
        
            <div class="info mt-5">
                <p>
                    Have an account already? <a class="sign-up-in-link" href="{% url 'story9:login' %}"><strong>Sign in.</strong></a>
                </p>
            </div>
        </div>
    </div> 
</div>

{% endblock content %}